import Head from 'next/head'
import Header from '../components/header'
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';


export default function App({ Component, pageProps }) {
  return(
    <>
     <Head>
        <title>KALAI TN 37</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

    <Component {...pageProps} />
    </>
  ) 
}
