import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import HomePage from './home/home';


export default function Home() {
  return (
    <>
      <Head>
        <title>KALAI TN 37</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  )
}
